### ISSUE TITLE
Armv6 binary for node10

### ISSUE THREAD

**Issue by Muzzamil1** [robertsLando/pkg-binaries#3]
Hi!
I am using
node version == v10.16.0
pkg version == 4.4.0
Raspberry pi zero w == Linux_armv6
It just hangs at the `make`

![Error in Pi zero](https://user-images.githubusercontent.com/53085438/67179191-01890100-f3ef-11e9-8a2c-4371ddd84c69.png)

After many hours `make `still did not progress.
Is there any way I can use the NodeJS that is already installed or can you please upload the binaries for Linux-armv6 with node10?

**Comment by robertsLando** [comment]
It doesn’t hangs it just takes very very long time (depends on the hardware but on my pc it takes even 10 hours or more). Try using the already existing node 10 version 

Daniel

**Comment by Muzzamil1** [comment]
Appreciate the quick response.
On your repo https://github.com/robertsLando/pkg-binaries/tree/master/arm32
There are binaries:

- v8.16.0-linux-armv6 

- v10.4.1-alpine-armv6 

but not with v10 for Linux-armv6. Can you please tell me where can I find binaries of node 10 version for Linux armv6?

**Comment by robertsLando** [comment]
Try using the 10.4 armv6 and rename it as armv7, place it in the pkg cache folder and try to build 

Daniel

**Comment by Muzzamil1** [comment]
Ok, Thanks.

**Comment by Muzzamil1** [comment]
Hi, @robertsLando 
I was trying to compile the binaries and almost after 24 hours I got this Error 
```
pi@raspberrypi:~/nodeIntoExe $ pkg . --targets linux-armv6
> pkg@4.4.0
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v10.15.3-linux-armv6 [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v1                                                                             0.15.3-linux-armv6
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v10.15.3-linux-armv6"}
> Not found in GitHub releases:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v10.15.3-linux-armv6"}
> Building base binary from source:
  built-v10.15.3-linux-armv6
> Cloning Node.js repository from GitHub...
  git                          [====================] 100%
> Checking out v10.15.3
> Applying patches
> Compiling Node.js from sources...
  make                         [                    ] 0%


  cc -o /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/obj.target/nghttp2/deps/ng                                                                                http2/lib/nghttp2_queue.o ../deps/nghttp2/lib/nghttp2_queue.c '-D_U_=' '-DBUI                                                                                LDING_NGHTTP2' '-DNGHTTP2_STATICLIB' -I../deps/nghttp2/lib/includes  -pthread                                                                                 -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer  -MMD -MF /t                                                                                mp/C2Z1oUM731YDEEKMWFlr/node/out/Release/.deps//tmp/C2Z1oUM731YDEEKMWFlr/node                                                                                /out/Release/obj.target/nghttp2/deps/nghttp2/lib/nghttp2_queue.o.d.raw   -c
  cc -o /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/obj.target/nghttp2/deps/ng                                                                                http2/lib/nghttp2_rcbuf.o ../deps/nghttp2/lib/nghttp2_rcbuf.c '-D_U_=' '-DBUI                                                                                LDING_NGHTTP2' '-DNGHTTP2_STATICLIB' -I../deps/nghttp2/lib/includes  -pthread                                                                                 -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer  -MMD -MF /t                                                                                mp/C2Z1oUM731YDEEKMWFlr/node/out/Release/.deps//tmp/C2Z1oUM731YDEEKMWFlr/node                                                                                /out/Release/obj.target/nghttp2/deps/nghttp2/lib/nghttp2_rcbuf.o.d.raw   -c
  cc -o /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/obj.target/nghttp2/deps/ng                                                                                http2/lib/nghttp2_session.o ../deps/nghttp2/lib/nghttp2_session.c '-D_U_=' '-                                                                                DBUILDING_NGHTTP2' '-DNGHTTP2_STATICLIB' -I../deps/nghttp2/lib/includes  -pth                                                                                read -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer  -MMD -M                                                                                F /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/.deps//tmp/C2Z1oUM731YDEEKMWFlr/                                                                                node/out/Release/obj.target/nghttp2/deps/nghttp2/lib/nghttp2_session.o.d.raw                                                                                   -c
  cc -o /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/obj.target/nghttp2/deps/ng                                                                                http2/lib/nghttp2_stream.o ../deps/nghttp2/lib/nghttp2_stream.c '-D_U_=' '-DB                                                                                UILDING_NGHTTP2' '-DNGHTTP2_STATICLIB' -I../deps/nghttp2/lib/includes  -pthre                                                                                ad -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer  -MMD -MF                                                                                 /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/.deps//tmp/C2Z1oUM731YDEEKMWFlr/no                                                                                de/out/Release/obj.target/nghttp2/deps/nghttp2/lib/nghttp2_stream.o.d.raw   -                                                                                c
  cc -o /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/obj.target/nghttp2/deps/ng                                                                                http2/lib/nghttp2_submit.o ../deps/nghttp2/lib/nghttp2_submit.c '-D_U_=' '-DB                                                                                UILDING_NGHTTP2' '-DNGHTTP2_STATICLIB' -I../deps/nghttp2/lib/includes  -pthre                                                                                ad -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer  -MMD -MF                                                                                 /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/.deps//tmp/C2Z1oUM731YDEEKMWFlr/no                                                                                de/out/Release/obj.target/nghttp2/deps/nghttp2/lib/nghttp2_submit.o.d.raw   -                                                                                c
  cc -o /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/obj.target/nghttp2/deps/ng                                                                                http2/lib/nghttp2_version.o ../deps/nghttp2/lib/nghttp2_version.c '-D_U_=' '-                                                                                DBUILDING_NGHTTP2' '-DNGHTTP2_STATICLIB' -I../deps/nghttp2/lib/includes  -pth                                                                                read -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer  -MMD -M                                                                                F /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/.deps//tmp/C2Z1oUM731YDEEKMWFlr/                                                                                node/out/Release/obj.target/nghttp2/deps/nghttp2/lib/nghttp2_version.o.d.raw                                                                                   -c
  rm -f /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/obj.target/deps/nghttp2/li                                                                                bnghttp2.a && ar crsT /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/obj.target/d                                                                                eps/nghttp2/libnghttp2.a /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/obj.targe                                                                                t/nghttp2/deps/nghttp2/lib/nghttp2_buf.o /tmp/C2Z1oUM731YDEEKMWFlr/node/out/R                                                                                elease/obj.target/nghttp2/deps/nghttp2/lib/nghttp2_callbacks.o /tmp/C2Z1oUM73                                                                                1YDEEKMWFlr/node/out/Release/obj.target/nghttp2/deps/nghttp2/lib/nghttp2_debu                                                                                g.o /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/obj.target/nghttp2/deps/nghttp                                                                                2/lib/nghttp2_frame.o /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/obj.target/n                                                                                ghttp2/deps/nghttp2/lib/nghttp2_hd.o /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Relea                                                                                se/obj.target/nghttp2/deps/nghttp2/lib/nghttp2_hd_huffman.o /tmp/C2Z1oUM731YD                                                                                EEKMWFlr/node/out/Release/obj.target/nghttp2/deps/nghttp2/lib/nghttp2_hd_huff                                                                                man_data.o /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/obj.target/nghttp2/deps                                                                                /nghttp2/lib/nghttp2_helper.o /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/obj.                                                                                target/nghttp2/deps/nghttp2/lib/nghttp2_http.o /tmp/C2Z1oUM731YDEEKMWFlr/node                                                                                /out/Release/obj.target/nghttp2/deps/nghttp2/lib/nghttp2_map.o /tmp/C2Z1oUM73                                                                                1YDEEKMWFlr/node/out/Release/obj.target/nghttp2/deps/nghttp2/lib/nghttp2_mem.                                                                                o /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/obj.target/nghttp2/deps/nghttp2/                                                                                lib/nghttp2_npn.o /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/obj.target/nghtt                                                                                p2/deps/nghttp2/lib/nghttp2_option.o /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Relea                                                                                se/obj.target/nghttp2/deps/nghttp2/lib/nghttp2_outbound_item.o /tmp/C2Z1oUM73                                                                                1YDEEKMWFlr/node/out/Release/obj.target/nghttp2/deps/nghttp2/lib/nghttp2_pq.o                                                                                 /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/obj.target/nghttp2/deps/nghttp2/l                                                                                ib/nghttp2_priority_spec.o /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/obj.tar                                                                                get/nghttp2/deps/nghttp2/lib/nghttp2_queue.o /tmp/C2Z1oUM731YDEEKMWFlr/node/o                                                                                ut/Release/obj.target/nghttp2/deps/nghttp2/lib/nghttp2_rcbuf.o /tmp/C2Z1oUM73                                                                                1YDEEKMWFlr/node/out/Release/obj.target/nghttp2/deps/nghttp2/lib/nghttp2_sess                                                                                ion.o /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/obj.target/nghttp2/deps/nght                                                                                tp2/lib/nghttp2_stream.o /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/obj.targe                                                                                t/nghttp2/deps/nghttp2/lib/nghttp2_submit.o /tmp/C2Z1oUM731YDEEKMWFlr/node/ou                                                                                t/Release/obj.target/nghttp2/deps/nghttp2/lib/nghttp2_version.o
  g++ -o /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/obj.target/node/src/node_                                                                                main.o ../src/node_main.cc '-D__POSIX__' '-DNODE_USE_V8_PLATFORM=1' '-DNODE_H                                                                                AVE_I18N_SUPPORT=1' '-DNODE_HAVE_SMALL_ICU=1' '-DHAVE_OPENSSL=1' '-DUCONFIG_N                                                                                O_SERVICE=1' '-DUCONFIG_NO_REGULAR_EXPRESSIONS=1' '-DU_ENABLE_DYLOAD=0' '-DU_                                                                                STATIC_IMPLEMENTATION=1' '-DU_HAVE_STD_STRING=1' '-DUCONFIG_NO_BREAK_ITERATIO                                                                                N=0' '-DHTTP_PARSER_STRICT=0' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64'                                                                                 '-D_POSIX_C_SOURCE=200112' '-DNGHTTP2_STATICLIB' -I../src -I../deps/v8/includ                                                                                e -I../deps/v8/include -I../deps/icu-small/source/i18n -I../deps/icu-small/so                                                                                urce/common -I../deps/zlib -I../deps/http_parser -I../deps/cares/include -I..                                                                                /deps/uv/include -I../deps/nghttp2/lib/includes -I../deps/openssl/openssl/inc                                                                                lude  -pthread -Wall -Wextra -Wno-unused-parameter -Wall -Wextra -Wno-unused-                                                                                parameter -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y                                                                                 -MMD -MF /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/.deps//tmp/C2Z1oUM731YDEE                                                                                KMWFlr/node/out/Release/obj.target/node/src/node_main.o.d.raw   -c
  g++ -o /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/node -pthread -rdynamic -                                                                                Wl,--whole-archive,/tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/obj.target/libn                                                                                ode.a -Wl,--no-whole-archive -Wl,--whole-archive,/tmp/C2Z1oUM731YDEEKMWFlr/no                                                                                de/out/Release/obj.target/deps/zlib/libzlib.a -Wl,--no-whole-archive -Wl,--wh                                                                                ole-archive,/tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/obj.target/deps/uv/lib                                                                                uv.a -Wl,--no-whole-archive -Wl,-z,noexecstack -Wl,--whole-archive /tmp/C2Z1o                                                                                UM731YDEEKMWFlr/node/out/Release/obj.target/deps/v8/gypfiles/libv8_base.a -Wl                                                                                ,--no-whole-archive -Wl,-z,relro -Wl,-z,now -Wl,--whole-archive,/tmp/C2Z1oUM7                                                                                31YDEEKMWFlr/node/out/Release/obj.target/deps/openssl/libopenssl.a -Wl,--no-w                                                                                hole-archive -pthread  -Wl,--start-group /tmp/C2Z1oUM731YDEEKMWFlr/node/out/R                                                                                elease/obj.target/node/src/node_main.o /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Rel                                                                                ease/obj.target/libnode.a /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/obj.targ                                                                                et/deps/v8/gypfiles/libv8_libplatform.a /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Re                                                                                lease/obj.target/tools/icu/libicui18n.a /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Re                                                                                lease/obj.target/deps/zlib/libzlib.a /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Relea                                                                                se/obj.target/deps/http_parser/libhttp_parser.a /tmp/C2Z1oUM731YDEEKMWFlr/nod                                                                                e/out/Release/obj.target/deps/cares/libcares.a /tmp/C2Z1oUM731YDEEKMWFlr/node                                                                                /out/Release/obj.target/deps/uv/libuv.a /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Re                                                                                lease/obj.target/deps/nghttp2/libnghttp2.a /tmp/C2Z1oUM731YDEEKMWFlr/node/out                                                                                /Release/obj.target/deps/openssl/libopenssl.a /tmp/C2Z1oUM731YDEEKMWFlr/node/                                                                                out/Release/obj.target/deps/v8/gypfiles/libv8_base.a /tmp/C2Z1oUM731YDEEKMWFl                                                                                r/node/out/Release/obj.target/deps/v8/gypfiles/libv8_libbase.a /tmp/C2Z1oUM73                                                                                1YDEEKMWFlr/node/out/Release/obj.target/deps/v8/gypfiles/libv8_libsampler.a /                                                                                tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/obj.target/tools/icu/libicuucx.a /t                                                                                mp/C2Z1oUM731YDEEKMWFlr/node/out/Release/obj.target/tools/icu/libicudata.a /t                                                                                mp/C2Z1oUM731YDEEKMWFlr/node/out/Release/obj.target/tools/icu/libicustubdata.                                                                                a /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/obj.target/deps/v8/gypfiles/libv                                                                                8_snapshot.a -ldl -lrt -lm -Wl,--end-group
/usr/bin/ld: /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/obj.target/node_lib/s                                                                                rc/bootstrapper.o: in function `node::PromiseRejectCallback(v8::PromiseReject                                                                                Message)':
bootstrapper.cc:(.text+0x400): undefined reference to `__atomic_fetch_add_8'
/usr/bin/ld: bootstrapper.cc:(.text+0x498): undefined reference to `__atomic_                                                                                fetch_add_8'
/usr/bin/ld: bootstrapper.cc:(.text+0x4c4): undefined reference to `__atomic_                                                                                load_8'
/usr/bin/ld: bootstrapper.cc:(.text+0x4dc): undefined reference to `__atomic_                                                                                load_8'
/usr/bin/ld: bootstrapper.cc:(.text+0x5c8): undefined reference to `__atomic_                                                                                load_8'
/usr/bin/ld: bootstrapper.cc:(.text+0x5e0): undefined reference to `__atomic_                                                                                load_8'
collect2: error: ld returned 1 exit status
make[1]: *** [node.target.mk:188: /tmp/C2Z1oUM731YDEEKMWFlr/node/out/Release/                                                                                node] Error 1
rm 46ede24a3fbce57c79789f17c8c120bbdaabf612.intermediate 47b2d47efd8ff57e18e4                                                                                db66a94372c4bcb2f9a6.intermediate
make: *** [Makefile:99: node] Error 2
  make                         [====================] 100%
> Error! Error: make failed with code 2
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/pkg/node_modules                                                                                /pkg-fetch/lib-es5/spawn.js:68:23)
    at ChildProcess.emit (events.js:203:15)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:606:12)
```
Any idea why am I getting this error?

**Comment by robertsLando** [comment]
Instead of using that command I suggest you to first build node using the tool provided with this repo. Just type ./build and select the distrubution wanted, edit the sh file with the nodejs version you want

Daniel

**Comment by Muzzamil1** [comment]
Ok, thanks.
